<div class="task-repeater generic-repeater">
    <div class="form-group">
        <div data-repeater-list="json_data">
            <div data-repeater-item>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label class="col-form-label required"><?php echo __('app.task.task_name') ?></label>
                        <div>
                            <input type="text" class="form-control tag-input" required placeholder="<?php echo __('app.task.task_name') ?>" name="name" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="col-form-label"><?php echo __('app.common.type') ?></label>
                        <div class="row">
                            <div class="col-lg-10">
                                <select name="type" data-placeholder="<?php __ss('app.common.select_type') ?>" class="form-select" required>
                                    <?php foreach ($taskTypes as $taskType) : ?>
                                        <option data-badge-color="<?php echo $taskType['color'] ?>" value="<?php echo $taskType['id'] ?>">
                                            <?php echo $taskType['name'] ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="col-lg-2 text-end">
                                <a href="javascript:;" data-repeater-delete class="btn btn-sm btn-light-danger mt-1"><i class="la la-trash-o"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="javascript:;" data-repeater-create class="btn btn-sm btn-light-primary btn-create-task"><i class="la la-plus"></i><?php echo __('app.task.add_task') ?></a>
    </div>
</div>