<svg class="icon-booklet-layout" xmlns="http://www.w3.org/2000/svg" viewBox="28 11 85 122">
  <defs>
    <style>
      .cls-1 {
        fill: #7e8299;
      }

      .cls-2 {
        fill: #ededed;
      }
    </style>
  </defs>
  <rect class="cls-2" x="28.78" y="11.34" width="84.18" height="119.06" rx="4.25" ry="4.25"/>
  <g>
    <rect class="cls-1" x="32.79" y="15.76" width="35.82" height="34.27" rx="4.25" ry="4.25"/>
    <rect class="cls-1" x="73.12" y="15.76" width="35.82" height="34.27" rx="4.25" ry="4.25"/>
  </g>
  <g>
    <rect class="cls-1" x="32.79" y="91.71" width="35.82" height="34.27" rx="4.25" ry="4.25"/>
    <rect class="cls-1" x="73.12" y="91.71" width="35.82" height="34.27" rx="4.25" ry="4.25"/>
  </g>
  <rect class="cls-1" x="32.79" y="53.73" width="76.14" height="34.27" rx="4.25" ry="4.25"/>
</svg>