<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>
            html,body { 
                padding: 0; margin:0; height: 100%; 
            }
        </style>
    </head>
    <body>
        <div style="font-family:Arial,Helvetica,sans-serif; line-height: 18px; font-weight: normal; font-size: 15px; color: #2F3044; min-height: 100%; margin:0; padding:0; width:100%; background-color:#f7f7f7">
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;margin:0 auto; padding:0; max-width:600px">
                <tbody>
                    <tr>
                        <td align="center" valign="center" style="text-align:center; padding-top: 40px; padding-bottom: 20px;">
                            <a href="<?php echo $params['SITE.URL'] ?>" rel="noopener" target="_blank">
                                <img alt="Logo" src="<?php echo $params['SITE.URL'] ?><?php echo $params['MAIL.LOGO_URL'] ?><?php echo '?v=' . RESOURCES_VERSION ?>" style="max-width: 270px;" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td align="left" valign="center">
                            <div style="text-align:left; margin: 0 20px; padding: 40px; padding-bottom: 20px; background-color:#ffffff; border-radius: 6px;">   
