<?php $this->insert("inc/header/head", get_defined_vars()); ?>
<!--begin::Body-->
<body id="page-login" class="header-fixed header-mobile-fixed subheader-enabled page-loading">
    <!--begin::Main-->
    <div class="d-flex flex-column flex-root">
        <!--begin::Login-->
        <div class="login login-1 login-signin-on d-flex flex-column flex-lg-row flex-column-fluid bg-light" id="kt_login">
            <!--begin::Aside
            <div class="login-aside d-flex flex-row-auto bgi-size-cover bgi-no-repeat p-10 p-lg-10">
            </div>
            -->
            <!--begin::Aside-->
            <!--begin::Content-->
            <div class="d-flex flex-column flex-row-fluid position-relative overflow-hidden">
                <!--end::Content header-->
                <!--begin::Content body-->
                <div class="d-flex flex-column-fluid flex-center mt-md-10 mt-lg-0 p-7">
                    <?php $this->insert("inc/common/messages", compact('messages')); ?>
                    <?php $this->insert($view, get_defined_vars()); ?>
                </div>
                <!--end::Content body-->   	
            </div>
            <!--end::Content-->
        </div>
        <!--end::Login-->
    </div>
    <?php $this->insert("inc/footer/footer_menu"); ?>                
    <?php $this->insert("inc/footer/footer", get_defined_vars()); ?>   

