<div class="row mb-2">
    <div class="form-item">
        <div class="d-flex align-items-center mt-3 radio-list">
            <label class="form-check form-check-custom form-check-inline me-10">
                <input class="form-check-input" name="cover_type" type="radio" value="select" allow-save-invalid>
                <span class="fw-semibold ps-3 fs-6"><?= __('app.booklet.cover_select') ?></span>
            </label>
            <label class="form-check form-check-custom form-check-inline">
                <input class="form-check-input" name="cover_type" type="radio" value="upload" allow-save-invalid>
                <span class="fw-semibold ps-3 fs-6"><?= __('app.booklet.cover_upload') ?></span>
            </label>
        </div>
    </div>
</div>

<div class="cover-select-container pb-4">
    <div class="image-select-container form-item">
        <div class="d-flex flex-wrap align-content-around mt-2 mh-400px">
            <?php foreach ($coverImages as $i => $image): ?>
                <div class="image-select radio-list">
                    <input type="radio"
                        name="cover_file_id"
                        id="<?= 'cover_img_' . $i ?>"
                        value="<?= $image['id'] ?>">
                    <label for="<?= 'cover_img_' . $i ?>"></label>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<div class="cover-upload-container pb-4">
    <?php $this->insert("inc/common/image_upload", ['id' => 'cover-upload', 'title' => __('app.common.cover'), 'inputName' => 'cover', 'recommendedDimensions' => '2550px x 3613px']) ?>
</div>

<?php if ($coverFile): ?>
    <div class="pb-4">
        <a href="" class="btn btn-link cover-source-download" target="_blank"><?= __('app.booklet.cover_file_download') ?></a>
    </div>
<?php endif; ?>