<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
        .page {
            page-break-after: always;
            padding: <?php echo $pageMargin ?>;
        }

        .page:last-child {
            page-break-after: unset;
        }

        html {
            margin: 0;
        }

        .product,
        .bg-image {
            position: absolute;
        }

        .bg-image {
            width: 100%;
            height: 100%;
        }

        .position-2 {
            width: 100%;
            height: 50%;
        }

        .position-3 {
            width: 100%;
            height: calc(100% / 3);
        }

        .position-6 {
            width: 50%;
            height: calc(100% / 3);
        }

        .qr {
            width: 155px;
            height: 155px;
            position: absolute;
            z-index: 9999999;
            bottom: 93px;
            right: 93px;
            padding: 15px;
            background-color: white;
        }

        .product .qr img {
            width: 100%;
            height: 100%;
        }

        .product-img,
        .bg-image-img {
            position: absolute;
            left: -<?php echo $border ?>;
            top: -<?php echo $border ?>;
            width: calc(100% + 2 * <?php echo $border ?>);
            height: calc(100% + 2 * <?php echo $border ?>);
        }

        .type-CMYK .visible-area {
            position: relative;
            top: <?php echo $border ?>;
            left: <?php echo $border ?>;
            width: calc(100% - 2 * <?php echo $border ?>);
            height: calc(100% - 2 * <?php echo $border ?>);
        }

        .cut-mark {
            position: absolute;
        }

        .cut-mark.top-left,
        .cut-mark.top-right,
        .cut-mark.bottom-left,
        .cut-mark.bottom-right {
            background-color: red;
            width: calc(0.5 * <?php echo $pageMargin ?>);
            height: 6px;
        }

        .cut-mark.top-left,
        .cut-mark.top-right {
            top: calc(<?php echo $pageMargin ?> + <?php echo $border ?>);
        }

        .cut-mark.bottom-left,
        .cut-mark.bottom-right {
            bottom: calc(<?php echo $pageMargin ?> + <?php echo $border ?>);
        }

        .cut-mark.top-left,
        .cut-mark.bottom-left {
            left: 0;
        }

        .cut-mark.top-right,
        .cut-mark.bottom-right {
            right: 0;
        }

        .cut-mark.left-top,
        .cut-mark.left-bottom,
        .cut-mark.right-top,
        .cut-mark.right-bottom {
            background-color: red;
            height: calc(0.5 * <?php echo $pageMargin ?>);
            width: 6px;
        }

        .cut-mark.left-top,
        .cut-mark.left-bottom {
            left: calc(<?php echo $pageMargin ?> + <?php echo $border ?>);
        }

        .cut-mark.right-top,
        .cut-mark.right-bottom {
            right: calc(<?php echo $pageMargin ?> + <?php echo $border ?>);
        }

        .cut-mark.right-top,
        .cut-mark.left-top {
            top: 0;
        }

        .cut-mark.left-bottom,
        .cut-mark.right-bottom {
            bottom: 0;
        }

        .type-RGB .cut-mark {
            display: none;
        }

        .type-RGB .product,
        .type-RGB .bg-image {
            overflow: hidden;
        }

        .type-CMYK .product-img-container {
            overflow: hidden;
        }

        /* Position 2 */
        .type-CMYK .position-2 .product-img-container {
            margin-left: -<?php echo $border ?>;
            width: calc(100% + 2 * <?php echo $border ?>);
            height: calc(100% + <?php echo $border ?>);
        }

        .type-CMYK .position-2:first-child .product-img-container {
            margin-top: -<?php echo $border ?>;
        }

        .type-CMYK .position-2:last-child .product-img-container {
            margin-bottom: -<?php echo $border ?>;
        }

        /* Position 3 */
        .type-CMYK .position-3 .product-img-container {
            margin-left: -<?php echo $border ?>;
            width: calc(100% + 2 * <?php echo $border ?>);
            height: 100%;
        }

        .type-CMYK .position-3:first-child .product-img-container {
            margin-top: -<?php echo $border ?>;
            height: calc(100% + <?php echo $border ?>);
        }

        .type-CMYK .position-3:last-child .product-img-container {
            margin-bottom: -<?php echo $border ?>;
            height: calc(100% + <?php echo $border ?>);
        }

        /* Position 6 */
        .type-CMYK .position-6 .product-img-container {
            width: calc(100% + <?php echo $border ?>);
            height: 100%;
        }

        .type-CMYK .position-6.position-6-l .product-img-container {
            margin-left: -<?php echo $border ?>;
        }

        .type-CMYK .position-6.position-6-r .product-img-container {
            margin-right: -<?php echo $border ?>;
        }

        .type-CMYK .position-6:nth-child(1) .product-img-container,
        .type-CMYK .position-6:nth-child(1) + .position-6:nth-child(2) .product-img-container {
            margin-top: -<?php echo $border ?>;
            height: calc(100% + <?php echo $border ?>);
        }

        .type-CMYK .position-6.position-6-last-row .product-img-container {
            margin-bottom: -<?php echo $border ?>;
            height: calc(100% + <?php echo $border ?>);
        }
    </style>
</head>
<?php
$positions = [
    '2_1' => ['x' => '0', 'y' => '0'],
    '2_2' => ['x' => '0', 'y' => '50%'],
    '3_1' => ['x' => '0', 'y' => '0'],
    '3_2' => ['x' => '0', 'y' => 'calc(100% / 3)'],
    '3_3' => ['x' => '0', 'y' => 'calc(100% / 3 * 2)'],
    '6_1' => ['x' => '0', 'y' => '0'],
    '6_2' => ['x' => '50%', 'y' => '0'],
    '6_3' => ['x' => '0', 'y' => 'calc(100% / 3)'],
    '6_4' => ['x' => '50%', 'y' => 'calc(100% / 3)'],
    '6_5' => ['x' => '0', 'y' => 'calc(100% / 3 * 2)'],
    '6_6' => ['x' => '50%', 'y' => 'calc(100% / 3 * 2)'],
];

$layouts = [];
$layouts[1] = ['2_1', '2_2']; // 1/2 + 1/2
$layouts[2] = ['3_1', '3_2', '3_3']; // 1/3 + 1/3 + 1/3
$layouts[3] = ['6_1', '6_2', '3_2', '3_3']; // 1/3x2 + 1/3 + 1/3
$layouts[4] = ['6_1', '6_2', '6_3', '6_4', '3_3']; // 1/3x2 + 1/3x2 + 1/3
$layouts[5] = ['6_1', '6_2', '3_2', '6_5', '6_6']; // 1/3x2 + 1/3 + 1/3x2
$layouts[6] = ['6_1', '6_2', '6_3', '6_4', '6_5', '6_6']; // 1/3x2 + 1/3x2 + 1/3x2
$layouts[7] = ['3_1', '6_3', '6_4', '3_3']; // 1/3 + 1/3x2 + 1/3
$layouts[8] = ['3_1', '6_3', '6_4', '6_5', '6_6']; // 1/3 + 1/3x2 + 1/3x2
$layouts[9] = ['3_1', '3_2', '6_5', '6_6']; // 1/3 + 1/3 + 1/3x2

?>


<body class="type-<?php echo $type ?>">
    <?php for ($page = array_key_first($booklet['pages']); $page <= array_key_last($booklet['pages']); $page++): ?>
        <div class="page page-<?php echo $page ?>">
            <div class="visible-area">
                <?php if (!empty($booklet['pages'][$page]['image'])): ?>
                    <div class="bg-image">
                        <img class="bg-image-img" src='<?php echo $booklet['pages'][1]['image'] ?>'>
                    </div>
                <?php else: ?>
                    <?php $currentLayout = $booklet['page' . $page . '_booklet_layout_id']; ?>
                    <?php foreach ($booklet['pages'][$page] as $i => $product): ?>
                        <?php $currentPosition = $layouts[$currentLayout][$i]; ?>
                        <?php $position = $positions[$currentPosition] ?>
                        <div style="top: <?php echo $position['y'] ?>; left: <?php echo $position['x'] ?>" class="product position-<?php echo $currentPosition[0] ?> 
                            <?php if ($currentPosition[0] == '6'): ?>
                                position-6-<?php echo intval($currentPosition[2]) % 2 == 0 ? 'r' : 'l' ?>
                                <?php if (($i == (count($booklet['pages'][$page]) - 2) && intval($currentPosition[2]) % 2 != 0) || ($i == (count($booklet['pages'][$page]) - 1) && intval($currentPosition[2]) % 2 == 0)): ?> position-6-last-row<?php endif; ?>
                            <?php endif; ?>" 
                        >
                            <?php if (!empty($product['qr'])): ?>
                                <div class="qr">
                                    <img src='<?php echo $product['qr']; ?>'>
                                </div>
                            <?php endif; ?>
                            <div class="product-img-container">
                                <img class="product-img" src='<?php echo $product['image'] ?>'>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>

            <span class="cut-mark top-left"></span>
            <span class="cut-mark top-right"></span>
            <span class="cut-mark bottom-left"></span>
            <span class="cut-mark bottom-right"></span>
            <span class="cut-mark left-top"></span>
            <span class="cut-mark left-bottom"></span>
            <span class="cut-mark right-top"></span>
            <span class="cut-mark right-bottom"></span>
        </div>
    <?php endfor; ?>
</body>

</html>