<div class="login-form login-signin">
<div class="text-center text-dark mb-10">
    <a href="/"><img src="/app/img/logo.png?v=2" class="img-fluid mw-200px mw-sm-300px"></a>
        <h3 class="text-dark fs-1 fw-bold mt-10"><?php echo __('app.login.login') ?></h3>
        <div class="text-dark fs-7 fw-lighter px-10"><?php echo __('app.login.enter_password_text') ?></div>
    </div>

    <form method="POST" class="form" id="login-enter-password" action="/app/public/enter_password" data-js="LoginEnterPasswordForm">
        <?php $this->insert("inc/security/csrf_input", compact('csrf')); ?>
        <input type="hidden" name="token" value="<?php echo $data['token'] ?>"/>

        <div class="fv-row mb-10">
            <label class="form-label fs-6 fw-bold text-dark"><?php echo __('app.login.password') ?></label>

            <div class="input-icon-container">
                <a href="javascript:;" class="input-icon show-password"><i class="ki-outline ki-eye text-dark show-icon"></i><i class="ki-outline ki-eye-slash text-dark hide-icon d-none"></i></a>
                <input class="form-control form-control-lg form-control-solid bg-white border-primary rounded" type="password" name="password" required autocomplete="off" tabindex="1" />
            </div>
        </div>

        <div class="fv-row mb-10">
            <label class="form-label fs-6 fw-bold text-dark"><?php echo __('app.login.repeat_password') ?></label>

            <div class="input-icon-container">
                <a href="javascript:;" class="input-icon show-password"><i class="ki-outline ki-eye text-dark show-icon"></i><i class="ki-outline ki-eye-slash text-dark hide-icon d-none"></i></a>
                <input class="form-control form-control-lg form-control-solid bg-white border-primary rounded" type="password" name="password2" required autocomplete="off" tabindex="2" />
            </div>
        </div>

        <button type="submit" id="kt_login_enter_password_submit" class="btn btn-primary w-100 rounded"><?php echo __('app.login.password_send') ?></button>
    </form>
</div>