<div class="card mb-5 mb-xl-10" id="client-header" data-client-id="<?php echo $client['id'] ?>">
    <div class="card-body pt-9 pb-0">
        <div class="d-flex flex-wrap flex-sm-nowrap mb-3">
            <div class="flex-grow-1">
                <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                    <div class="d-flex flex-column">
                        <div class="d-flex align-items-center mb-2">
                            <span class="d-flex align-items-center fs-2 fw-500 me-1" id="client-fullname">
                                <?php echo $client['entity'] ?>
                            </span>
                        </div>

                        <div class="d-flex flex-wrap fs-6 mb-0 pe-2">
                            <div class="d-flex align-items-center text-muted me-5 mb-2">
                                <i class="las la-map-marker me-2 fs-3 text-primary"></i> <span id="client-location"><?php echo isset($client['city']) ? $client['city'] : '' ?> <?php echo isset($client['country_name']) ? ' (' . $client['country_name'] . ')' : '' ?></span>
                            </div>
                            <?php if (!empty($client['email'])) : ?>
                                <?php foreach ($client['email'] as $email) : ?>
                                    <div class="d-flex align-items-center mb-2 me-5 client-email">
                                        <i class="las la-envelope me-2 fs-3 text-primary"></i> <a class="text-muted text-hover-primary" href="mailto:<?php echo $email['email'] ?>" title="<?php __s($email['name']) ?>"><?php echo $email['email'] ?></a>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if (!empty($client['phone'])) : ?>
                                <?php foreach ($client['phone'] as $phone) : ?>
                                    <div class="d-flex align-items-center mb-2 me-5 client-phone">
                                        <i class="las la-phone me-2 fs-3 text-primary"></i> <a class="text-muted text-hover-primary" href="tel:<?php echo $phone['phone'] ?>" title="<?php __s($phone['name']) ?>"><?php echo $phone['phone'] ?></a>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav nav-stretch nav-line-tabs nav-line-tabs-2x fs-3 text-primary">
            <li class="nav-item mt-2">
                <a class="nav-link text-active-primary ms-0 me-10 py-5 <?php App\Util\CommonUtils::checkActive($menuClient, App\Constant\App\MenuSection::MenuClientData, 'active'); ?>" href="/app/<?php echo $entity ?>/form/<?php echo $client['id'] ?>"><?php echo __('app.user.personal_information') ?></a>
            </li>
            <li class="nav-item mt-2">
                <a class="nav-link text-active-primary ms-0 me-10 py-5 <?php App\Util\CommonUtils::checkActive($menuClient, App\Constant\App\MenuSection::MenuClientProcesses, 'active'); ?>" href="/app/<?php echo $entity ?>/processes/<?php echo $client['id'] ?>"><?php echo __('app.common.processes') ?></a>
            </li>
        </ul>
    </div>
</div>