<div class="card mb-5 mb-xl-10 shadow-sm" id="user-header" data-js="UserHeader" data-user-id="<?php echo $userId ?>">
    <div class="card-body pt-9 pb-0">
        <div class="d-flex flex-wrap flex-sm-nowrap mb-3">
            <div class="me-7 mb-4">
                <div class="symbol symbol-100px symbol-lg-160px symbol-fixed position-relative">
                    <img id="user-avatar" class="h-auto" />
                </div>
            </div>
            <div class="flex-grow-1">
                <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                    <div class="d-flex flex-column">
                        <div class="d-flex align-items-center mb-2">
                            <span class="fw-500 text-hover-primary fs-2 me-1" id="user-fullname"></span>                            
                        </div>                        
                        <div class="d-flex flex-wrap mb-4 pe-2">
                            <div class="d-flex align-items-center text-gray-400 me-5 mb-2">
                                <span class="badge fw-lighter" id="user-profile"></span>
                            </div>                            
                            <div class="d-flex align-items-center mb-2">
                                <i class="las la-envelope me-1 text-primary"></i> <a class="text-gray-400 text-hover-primary" id="user-email" href=""></a>
                            </div>                            
                        </div>
                    </div>
                </div>                
            </div>
            <!--end::Info-->
        </div>
        <?php if(false): ?>
            <!--begin::Navs-->
            <ul class="nav nav-stretch nav-line-tabs nav-line-tabs-2x fs-3 text-primary">
                <li class="nav-item mt-2">
                    <a class="nav-link text-active-primary ms-0 me-10 py-5 <?php App\Util\CommonUtils::checkActive($menu, App\Constant\App\MenuSection::MenuUserData, 'active'); ?>"  href="/app/<?php echo $entity ?>/form/<?php echo $userId ?>"><?php echo __('app.user.personal_information') ?></a>
                </li>
                <li class="nav-item mt-2">
                    <a class="nav-link text-active-primary ms-0 me-10 py-5 <?php App\Util\CommonUtils::checkActive($menu, App\Constant\App\MenuSection::MenuUserLogs, 'active'); ?>" href="/app/<?php echo $entity ?>/logs/<?php echo $userId ?>"><?php echo __('app.user.logs') ?></a>
                </li>            
            </ul>
        <?php endif; ?>
    </div>
</div>