<?php $this->start('filters') ?>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.tags') ?></label>
    <select data-placeholder="<?php __ss('app.tags') ?>" multiple class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="tags">
        <option value=" "></option>
        <?php foreach ($data['tags'] as $tag) : ?>
            <option value="<?= $tag['id'] ?>">
                <?= $tag['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<?php if (empty($processId)) : ?>
    <div class="col-sm-6 col-xl-3">
        <label class="form-label"><?= __('app.common.processes') ?></label>
        <select data-placeholder="<?php __ss('app.common.processes') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="process_id">
            <option value=""></option>
            <?php foreach ($data['processes'] as $process) : ?>
                <option value="<?= $process['id'] ?>">
                    <?= $process['name'] ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
<div class="col-sm-6 col-xl-3 profile-allow profile-A">
    <label class="form-label"><?= __('app.common.author') ?></label>
    <select data-placeholder="<?php __ss('app.common.author') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="creator_user_id">
        <option value=""></option>
        <?php foreach ($data['taskCreator'] as $creator) : ?>
            <option value="<?= $creator['id'] ?>">
                <?= $creator['fullname'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.type') ?></label>
    <select data-placeholder="<?php __ss('app.common.type') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="task_type_id">
        <option value=""></option>
        <?php foreach ($data['taskTypes'] as $type) : ?>
            <option value="<?= $type['id'] ?>">
                <?= $type['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.status') ?></label>
    <select data-placeholder="<?php __ss('app.common.status') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="task_status_id">
        <option value=""></option>
        <?php foreach ($data['taskStatuses'] as $status) : ?>
            <option value="<?= $status['id'] ?>">
                <?= $status['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-sm-6 col-xl-3 profile-allow profile-A">
    <label class="form-label"><?= __('app.task.payment_status') ?></label>
    <select data-placeholder="<?php __ss('app.common.status') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="payment_status_id">
        <option value=""></option>
        <?php foreach ($data['taskPaymentStatuses'] as $status) : ?>
            <option value="<?= $status['id'] ?>">
                <?= $status['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-md-6 col-xl-3">
    <label class="form-label"><?= __('app.task.date_task') ?></label>
    <div class="custom-datepicker input-daterange input-group">
        <input type="text" class="form-control form-control-sm datatables-column-search-filter mr-0 kt-input border-radius-right-0" id="datapicker-range-from" name="start" placeholder="<?php echo __('app.common.from') ?>" data-col-name="date_task" />
        <input type="text" class="form-control form-control-sm datatables-column-search-filter ml-0 kt-input border-radius-left-0" id="datapicker-range-to" name="end" placeholder="<?php echo __('app.common.to') ?>" data-col-name="date_task" />
    </div>
</div>
<div class="col-md-6 col-xl-3">
    <label class="form-label"><?= __('app.common.date_created') ?></label>
    <div class="custom-datepicker input-daterange input-group">
        <input type="text" class="form-control form-control-sm datatables-column-search-filter mr-0 kt-input border-radius-right-0" id="datapicker-range-from" name="start" placeholder="<?php echo __('app.common.from') ?>" data-col-name="date_created" />
        <input type="text" class="form-control form-control-sm datatables-column-search-filter ml-0 kt-input border-radius-left-0" id="datapicker-range-to" name="end" placeholder="<?php echo __('app.common.to') ?>" data-col-name="date_created" />
    </div>
</div>
<?php $this->stop() ?>


<?php $this->start('columns') ?>
<!-- Data priority corresponde a la prioridad para mostrarse visible o bajo el botón (+) en responsive -->
<th data-priority="1"><?php echo __('app.common.id') ?></th>
<th data-priority="1"><?= __ss('app.process') ?></th>
<th data-priority="1"><?= __ss('app.task.concept') ?></th>
<th></th>
<th data-priority="3"><?= __ss('app.common.type') ?></th>
<th data-priority="3"><?= __ss('app.common.status') ?></th>
<th data-priority="3" class="profile-allow profile-A"><?= __ss('app.task.payment_status') ?></th>
<th data-priority="4"><?= __ss('app.common.hours') ?></th>
<th data-priority="5"><?= __ss('app.common.author') ?></th>
<th data-priority="6"><?= __ss('app.task.date_task.short') ?></th>
<th data-priority="6"><?= __ss('app.common.date_created.short') ?></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th data-priority="1" class="text-center"></th>
<?php $this->stop() ?>

<?php if (isset($processId)) : ?>
    <div class="process-tasks" data-process-id="<?php echo $processId ?>">
        <?php $this->insert('/inc/common/datatable', ['entity' => 'task', 'btnAdd' => true, 'btnAddParam' => $processId, 'title' => __('app.common.tasks'), 'filters' => $this->section('filters'), 'columns' => $this->section('columns')]) ?>
    </div>
<?php else : ?>
    <?php $this->insert("inc/common/subheader", ['entity' => 'task', 'btnExport' => true, 'btnAdd' => true, 'menu' => $menu, 'breadcumb' => $breadcumb]); ?>
    <?php $this->insert('inc/common/datatable', ['entity' => 'task', 'columns' => $this->section('columns'), 'filters' => $this->section('filters')]); ?>
<?php endif; ?>