<?php $this->start('filters') ?>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.entity.product') ?></label>
    <select data-placeholder="<?php __ss('app.entity.product') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="product_id">
        <option value=""></option>
        <?php foreach ($data['products'] as $product) : ?>
            <option value="<?= $product['id'] ?>"><?= $product['name'] ?></option>
        <?php endforeach; ?>
    </select>
</div>

<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.status') ?></label>
    <select data-placeholder="<?php __ss('app.common.status') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="subproduct_status">
        <option value=""></option>
        <?php foreach ($data['subProductStatus'] as $status) : ?>
            <option value="<?= $status ?>"><?= __('app.subproduct.status.' . $status) ?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php $this->stop() ?>


<?php $this->start('columns') ?>
<!-- Añadimos tantos th como columnas con las que trabajamos en el datatable, si la columna está oculta, dejamos el th vacío -->
<!-- Data priority corresponde a la prioridad para mostrarse visible o bajo el botón (+) en responsive -->
<th data-priority="5"><?php echo __('app.common.id') ?></th>
<th data-priority="1"><?php echo __('app.common.name') ?></th>
<th data-priority="1"><?php echo __('app.entity.product') ?></th>
<th data-priority="2"><?= __ss('app.format') ?></th>
<th data-priority="3"><?= __ss('app.reference_code') ?></th>
<th data-priority="4"><?= __ss('app.common.date_created.short') ?></th>
<th></th>
<th></th>
<th></th>
<th data-priority="1" class="text-center"></th>

<?php $this->stop() ?>

<?php $this->insert("inc/common/subheader", ['entity' => 'subproduct', 'btnExport' => true, 'btnAdd' => true, 'menu' => $menu, 'breadcumb' => $breadcumb]); ?>
<?php $this->insert('inc/common/datatable', ['entity' => 'subproduct', 'columns' => $this->section('columns'), 'filters' => $this->section('filters')]); ?>