<form
    id="mt-product-form"
    class="d-none data-form"
    data-js="CustomProductForm"
    action="/app/custom_product/save/<?php echo \App\Constant\App\FormSaveMode::SaveAndContinue ?>"
    method="post"
    autocomplete="off"
    enctype="multipart/form-data">
    <?php
    $this->insert(
        "inc/common/subheader",
        [
            'entity' => 'product',
            'btnBack' => '/app/custom_products',
            'btnSave' => true,
            'menu' => $menu,
            'breadcumb' => $breadcumb
        ]
    );
    ?>
    <?php if (!empty($data['id'])): ?>
        <input type="hidden" name="id" value="<?php echo $data['id'] ?>" />
    <?php endif; ?>

    <?php if (!empty($data['parent_product_id'])): ?>
        <input type="hidden" name="parent_product_id" value="<?php echo $data['parent_product_id'] ?>" />
    <?php endif; ?>

    <?php $this->insert("product/inc/information", ['data' => $data, 'custom' => true]) ?>
</form>