<?php $this->start('filters') ?>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.type') ?></label>
    <select data-placeholder="<?php __ss('app.common.type') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="client_type_id">
        <option value=""></option>
        <?php foreach ($data['clientTypes'] as $type): ?>
            <option value="<?= $type['id'] ?>">
                <?= $type['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<?php $this->stop() ?>


<?php $this->start('columns') ?>
<!-- Añadimos tantos th como columnas con las que trabajamos en el datatable, si la columna está oculta, dejamos el th vacío -->
<!-- Data priority corresponde a la prioridad para mostrarse visible o bajo el botón (+) en responsive --> 
<th data-priority="1"><?= __ss('app.common.id') ?></th>
<th data-priority="1"><?= __ss('app.common.type') ?></th>
<th data-priority="1"><?= __ss('app.client.entity') ?></th>
<th data-priority="1"><?= __ss('app.common.processes') ?></th>
<th data-priority="4"><?= __ss('app.client.phone') ?></th>
<th data-priority="3"><?= __ss('app.client.email') ?></th>
<th data-priority="3"><?= __ss('app.common.country') ?></th>
<th data-priority="6"><?= __ss('app.common.date_created') ?></th>
<th></th>
<th data-priority="1" class="text-center"></th>
    <?php $this->stop() ?>

<?php $this->insert("inc/common/subheader", ['entity' => 'client', 'btnExport' => true, 'btnAdd' =>($_SESSION)['user']['user_profile_id'] == App\Constant\UserProfile::Administrator, 'menu' => $menu, 'breadcumb' => $breadcumb]); ?>
<?php $this->insert('inc/common/datatable', ['entity' => 'client', 'columns' => $this->section('columns'), 'filters' => $this->section('filters')]); ?>