<?php $this->start('filters') ?>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.author') ?></label>
    <select data-placeholder="<?php __ss('app.common.author') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="creator_user_id">
        <option value=""></option>
        <?php foreach ($data['processCreator'] as $creator) : ?>
            <option value="<?= $creator['id'] ?>">
                <?= $creator['fullname'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.type') ?></label>
    <select data-placeholder="<?php __ss('app.common.type') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="process_type_id">
        <option value=""></option>
        <?php foreach ($data['processTypes'] as $type) : ?>
            <option value="<?= $type['id'] ?>">
                <?= $type['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.common.status') ?></label>
    <select data-placeholder="<?php __ss('app.common.status') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="process_status_id">
        <option value=""></option>
        <?php foreach ($data['processStatuses'] as $status) : ?>
            <option value="<?= $status['id'] ?>">
                <?= $status['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="col-md-6 col-xl-3">
    <label class="form-label"><?= __('app.common.date_start') ?></label>
    <div class="custom-datepicker input-daterange input-group">
        <input type="text" class="form-control form-control-sm datatables-column-search-filter mr-0 kt-input border-radius-right-0" id="datapicker-range-from" name="start" placeholder="<?php echo __('app.common.from') ?>" data-col-name="date_start" />
        <input type="text" class="form-control form-control-sm datatables-column-search-filter ml-0 kt-input border-radius-left-0" id="datapicker-range-to" name="end" placeholder="<?php echo __('app.common.to') ?>" data-col-name="date_start" />
    </div>
</div>
<div class="col-md-6 col-xl-3">
    <label class="form-label"><?= __('app.common.date_end') ?></label>
    <div class="custom-datepicker input-daterange input-group">
        <input type="text" class="form-control form-control-sm datatables-column-search-filter mr-0 kt-input border-radius-right-0" id="datapicker-range-from" name="start" placeholder="<?php echo __('app.common.from') ?>" data-col-name="date_end" />
        <input type="text" class="form-control form-control-sm datatables-column-search-filter ml-0 kt-input border-radius-left-0" id="datapicker-range-to" name="end" placeholder="<?php echo __('app.common.to') ?>" data-col-name="date_end" />
    </div>
</div>
<div class="col-md-6 col-xl-3">
    <label class="form-label"><?= __('app.common.date_created') ?></label>
    <div class="custom-datepicker input-daterange input-group">
        <input type="text" class="form-control form-control-sm datatables-column-search-filter mr-0 kt-input border-radius-right-0" id="datapicker-range-from" name="start" placeholder="<?php echo __('app.common.from') ?>" data-col-name="date_created" />
        <input type="text" class="form-control form-control-sm datatables-column-search-filter ml-0 kt-input border-radius-left-0" id="datapicker-range-to" name="end" placeholder="<?php echo __('app.common.to') ?>" data-col-name="date_created" />
    </div>
</div>
<?php $this->stop() ?>


<?php $this->start('columns') ?>
<!-- Data priority corresponde a la prioridad para mostrarse visible o bajo el botón (+) en responsive -->
<th data-priority="1"><?php echo __('app.common.id') ?></th>
<th data-priority="1"><?= __ss('app.common.name') ?></th>
<th data-priority="4"><?= __ss('app.common.type') ?></th>
<th data-priority="3"><?= __ss('app.common.status') ?></th>
<th data-priority="3"><?= __ss('app.common.tasks') ?></th>
<th data-priority="5"><?= __ss('app.common.author') ?></th>
<th data-priority="4"><?= __ss('app.common.date_start') ?></th>
<th data-priority="4"><?= __ss('app.common.date_end') ?></th>
<th data-priority="6"><?= __ss('app.common.date_created') ?></th>
<th data-priority="6"><?= __ss('app.common.date_updated') ?></th>

<th></th>
<?php $this->stop() ?>

<div id="mt-client-form" class="client-processes" data-client-id="<?php echo $data['id'] ?>">
    <?php
    $this->insert(
        "inc/common/subheader",
        [
            'entity' => $entity,
            'btnBack' => '/app/' . $entity . 's',
            'btnSave' => true,
            'menu' => $menu,
            'breadcumb' => $breadcumb
        ]
    );
    ?>
    <?php $this->insert("client/inc/header_info", ['menuClient' => $menuClient, 'client' => empty($data['client']) ? null : $data['client'], 'entity' => $entity]); ?>
    <?php $this->insert('/inc/common/datatable', ['entity' => 'clientProcesses', 'btnAdd' => ($_SESSION)['user']['user_profile_id'] == App\Constant\UserProfile::Administrator, 'btnAddParam' => $data['client']['id'], 'title' => __('app.common.processes'), 'filters' => $this->section('filters'), 'columns' => $this->section('columns')]) ?>
</div>