<?php $this->start('filters') ?>
<div class="col-sm-6 col-xl-3">
    <label class="form-label"><?= __('app.entity.area') ?></label>
    <select data-placeholder="<?php __ss('app.entity.area') ?>" class="form-select form-select-sm datatables-column-search-filter kt-select2" data-col-name="area_id">
        <option value=""></option>
        <?php foreach ($data['areas'] as $area) : ?>
            <option value="<?= $area['id'] ?>"><?= $area['name'] ?></option>
        <?php endforeach; ?>
    </select>
</div>


<?php $this->stop() ?>


<?php $this->start('columns') ?>
<!-- Añadimos tantos th como columnas con las que trabajamos en el datatable, si la columna está oculta, dejamos el th vacío -->
<!-- Data priority corresponde a la prioridad para mostrarse visible o bajo el botón (+) en responsive -->
<th data-priority="5"><?php echo __('app.common.id') ?></th>
<th data-priority="1"><?php echo __('app.common.image') ?></th>
<th data-priority="3"><?= __ss('app.common.name') ?></th>
<th data-priority="4"><?= __ss('app.entity.area') ?></th>
<th data-priority="6"><?= __ss('app.entity.booklets') ?></th>
<th data-priority="6"><?= __ss('app.entity.subproducts') ?></th>
<th data-priority="7"><?= __ss('app.common.date_created.short') ?></th>
<th></th>
<th data-priority="1" class="text-center"></th>

<?php $this->stop() ?>

<?php $this->insert("inc/common/subheader", ['entity' => 'product', 'btnExport' => true, 'btnAdd' => true, 'menu' => $menu, 'breadcumb' => $breadcumb]); ?>
<?php $this->insert('inc/common/datatable', ['entity' => 'product', 'columns' => $this->section('columns'), 'filters' => $this->section('filters')]); ?>