<?php $this->start('columns') ?>
<!-- Añadimos tantos th como columnas con las que trabajamos en el datatable, si la columna está oculta, dejamos el th vacío -->
<!-- Data priority corresponde a la prioridad para mostrarse visible o bajo el botón (+) en responsive -->
<th data-priority="1"><?php echo __('app.common.id') ?></th>
<th data-priority="1"><?= __ss('app.common.name') ?></th>
<th data-priority="2"><?= __ss('app.main_language') ?></th>
<th data-priority="3"><?= __ss('app.qr_language') ?></th>
<th data-priority="4"><?= __ss('app.entity.products') ?></th>
<th data-priority="4"><?= __ss('app.common.users') ?></th>
<th data-priority="5"><?= __ss('app.common.date_created.short') ?></th>
<th data-priority="1" class="text-center"></th>

<?php $this->stop() ?>

<?php $this->insert("inc/common/subheader", ['entity' => 'market', 'btnExport' => true, 'btnAdd' => true, 'menu' => $menu, 'breadcumb' => $breadcumb]); ?>
<?php $this->insert('inc/common/datatable', ['entity' => 'market', 'columns' => $this->section('columns'), 'filters' => $this->section('filters')]); ?>