<?php $datatableId = "mt-" . App\Util\CommonUtils::camelCaseToUnderscore($entity, '-'); ?>
<div class="card card-custom datatable-container mb-10">
    <?php if (!empty($title)) : ?>
        <div class="card-header">
            <div class="card-title">
                <h3><?= $this->e($title) ?></h3>
            </div>
            <div class="card-toolbar d-print-none">
                <?php $this->insert('/inc/common/button_export', compact('datatableId')) ?>
                <?php if (isset($btnAdd)) : ?>
                    <?php $this->insert('/inc/common/button_add', compact('btnAdd', 'entity', 'btnAddParam')) ?>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="card-body">
        <form autocomplete="off">
            <div class="mb-7">
                <div class="card-toolbar">
                    <div class="row mb-4">
                        <div class="col-8 col-md-6 col-xl-3">
                            <?php $this->insert('/inc/common/button_search') ?>
                        </div>
                        <?php if (!empty($filters)) : ?>
                            <div class="col-4 col-md-6 offset-xl-3 d-flex justify-content-end" data-kt-user-table-toolbar="base">
                                <?php $this->insert('/inc/common/button_filter') ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="filter-section">
                        <div class="row mb-4">
                            <?= $filters ?>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button class="reset-filters btn btn-light btn-active-light-primary fw-semibold me-2 px-6" data-action="remove">
                                <span>
                                    <i class="las la-broom fs-2"></i>
                                    <span><?= __('app.common.reset_filters') ?></span>
                                </span>
                            </button>
                            <button class="btn btn-primary fw-semibold px-6" data-action="advanced-search">
                                <span>
                                    <i class="ki-outline ki-filter fs-2"></i>
                                    <span><?= __('app.common.filter') ?></span>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-hover gy-5 gs-7" id="<?= $datatableId ?>" <?php if (!empty($attributes)) : ?><?= $attributes ?><?php endif; ?> data-js="<?= App\Util\CommonUtils::underscoreToCamelCase($entity, '-') ?>Datatable">
                <thead>
                    <tr class="text-start text-muted fw-bold fs-7 text-uppercase gs-0">
                        <?= $columns ?>
                    </tr>
                </thead>
            </table>
        </form>
    </div>
</div>