<label class="col-form-label required"><?php echo $title; ?></label>
<div>
    <div class="image-input image-input-outline" id="<?php echo $id ?>" data-kt-image-input="true">
        <div class="image-input-wrapper w-200px h-200px"></div>
        <label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="change" data-bs-toggle="tooltip" title="<?php echo __('app.common.form.select_image') ?>">
            <i class="bi bi-pencil-fill fs-7"></i>
            <input type="file" name="<?php echo $inputName; ?>" accept="image/jpeg" required />
        </label>
    </div>
    <div class="form-text">
        <?php echo __('app.common.media_formats'); ?><br>
        <?php echo __('app.common.recommended_dimensions'); ?>: <?php echo $recommendedDimensions; ?>
    </div>
</div>