<div class="row">
    <div class="col-lg-6">
        <label class="col-form-label required"><?php echo __('app.user.address') ?></label>                
        <div>
            <input type="text" class="form-control" placeholder="<?php echo __('app.user.address') ?>" name="personal_information[address]" required maxlength="200" />
        </div>
    </div>
    <div class="col-lg-6">
        <label class="col-form-label required"><?php echo __('app.user.postalcode') ?></label>                
        <div>
            <input type="text" class="form-control" placeholder="<?php echo __('app.user.postalcode') ?>" id="user_postalcode" required maxlength="5" />
        </div>
    </div>
    <div class="col-lg-6">
        <label class="col-form-label required"><?php echo __('app.user.city') ?></label>                
        <div>
            <select name="personal_information[city_id]" data-placeholder="<?php __ss('app.user.select_postalcode') ?>" required class="form-select kt-select2"></select>
        </div>
    </div>
    <div class="col-lg-6">
        <label class="col-form-label required"><?php echo __('app.user.state') ?></label>                
        <div>
            <input disabled type="text" class="form-control" id="user_state" />
        </div>
    </div>
    <div class="col-lg-6">
        <label class="col-form-label required"><?php echo __('app.user.community') ?></label>                
        <div>
            <input disabled type="text" class="form-control" id="user_community" />
        </div>
    </div>
    <div class="col-lg-6">
        <label class="col-form-label required"><?php echo __('app.user.country') ?></label>                
        <div>
            <input disabled type="text" class="form-control" id="user_country" />
        </div>
    </div>
</div>