<div class="d-flex <?php if (empty($messageInline)): ?>d-none<?php endif; ?> align-items-center rounded py-5 px-5 bg-light-warning mb-6" id="message-inline">
    <span class="svg-icon svg-icon-3x svg-icon-warning me-5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="black"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="black"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="black"></rect></svg></span>
    <div class="text-gray-700">
        <?php if (!empty($messageInline)): ?><?php echo $messageInline; ?><?php endif; ?>
    </div>
</div>