<form
    id="mt-recipe-form"
    class="d-none data-form"
    data-js="RecipeForm"
    action="/app/recipe/save/<?php echo \App\Constant\App\FormSaveMode::SaveAndContinue ?>"
    method="post"
    autocomplete="off"
    data-default-market-id="<?php echo !empty($data['default_market_id']) ? $data['default_market_id'] : '' ?>">
    <?php
    $this->insert(
        "inc/common/subheader",
        [
            'entity' => 'recipe',
            'btnBack' => '/app/recipes',
            'btnSave' => true,
            'btnSaveAndGenerate' => true,
            'menu' => $menu,
            'breadcumb' => $breadcumb
        ]
    );
    ?>
    <?php if (!empty($data['id'])): ?>
        <input type="hidden" name="id" value="<?php echo $data['id'] ?>" />
    <?php endif; ?>

    <input type="hidden" class="json-data" name="json_data">

    <div class="stepper stepper-pills first" id="mt-recipe-stepper">
        <?php $this->insert("inc/common/stepper_nav", ['steps' => [
            __('app.common.step_info'),
            __('app.common.step_page_1_left'),
            __('app.common.step_page_1_right'),
            __('app.common.step_page_2_left'),
            __('app.common.step_page_2_right'),
            __('app.common.step_generate_pdf')
        ]]) ?>

        <div>
            <div class="current flex-column" data-kt-stepper-element="content">
                <div class="card card-custom card-sticky">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.main_information') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.common.name') ?></label>
                                <div>
                                    <input type="text" class="form-control" required placeholder="<?php echo __('app.common.name') ?>" name="name" maxlength="45" />
                                </div>
                            </div>

                            <?php if ($_SESSION['user']['user_profile_id'] == App\Constant\UserProfile::Administrator) : ?>
                                <div class="col-md-6">
                                    <label class="col-form-label required"><?php echo __('app.entity.market') ?></label>
                                    <div>
                                        <select name="market_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                            <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                            <?php foreach ($data['markets'] as $market): ?>
                                                <option value="<?php echo $market['id'] ?>">
                                                    <?php echo $market['name'] ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.entity.market') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="market_name" />
                                    </div>
                                </div>
                            <?php endif ?>

                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.visuals_language') ?></label>
                                <div>
                                    <select name="main_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['main_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>">
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <label class="col-form-label" for="show_qr"><?php echo __('app.common.show_qr') ?></label>
                                <div class="d-flex align-items-center">
                                    <div class="form-check form-check-solid form-switch">
                                        <input class="form-check-input w-45px h-30px" type="checkbox" id="show_qr" value="1" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <label class="col-form-label required"><?php echo __('app.qr_language') ?></label>
                                <div>
                                    <select name="qr_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['qr_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>">
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-form-label"><?php echo __('app.recipe.reference_code_type') ?></label>
                                <div class="form-item">
                                    <div class="d-flex flex-column justify-content-between mt-3 radio-list">
                                        <label class="form-check form-check-custom form-check-inline mb-2 text-nowrap">
                                            <input class="form-check-input" name="international" type="radio" value="<?= App\Constant\International::NationalCode ?>">
                                            <span class="fw-semibold ps-3 fs-6"><?= __('app.recipe.national_code') ?><?php $this->insert('inc/common/tooltip', ['tooltip' => $this->e('app.recipe.national_code_text')]); ?></span>
                                        </label>
                                        <label class="form-check form-check-custom form-check-inline mb-2 text-nowrap">
                                            <input class="form-check-input" name="international" type="radio" value="<?= App\Constant\International::InternationalCode ?>">
                                            <span class="fw-semibold ps-3 fs-6"><?= __('app.recipe.international_code') ?><?php $this->insert('inc/common/tooltip', ['tooltip' => $this->e('app.recipe.international_code_text')]); ?></span>
                                        </label>
                                        <label class="form-check form-check-custom form-check-inline text-nowrap">
                                            <input class="form-check-input" name="international" type="radio" value="<?= App\Constant\International::NoCode ?>">
                                            <span class="fw-semibold ps-3 fs-6"><?= __('app.recipe.no_code') ?></span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.recipe.code') ?><?php $this->insert('inc/common/tooltip', ['tooltip' => $this->e('app.recipe.code_text')]); ?></label>
                                <div>
                                    <input type="text" class="form-control" required placeholder="<?php echo __('app.recipe.code') ?>" name="code" minlength="9" maxlength="9" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (!empty($data['id'])): ?>
                    <div class="card card-custom card-sticky">
                        <div class="card-header">
                            <div class="card-title">
                                <h3><?php echo __('app.common.additional_info') ?></h3>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row profile-allow profile-A">

                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.creator') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="creator_name" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_created') ?></label>
                                    <div>
                                        <input class="form-control mt-date-created" disabled type="text">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_updated') ?></label>
                                    <div>
                                        <input class="form-control mt-date-updated" disabled type="text">
                                    </div>
                                </div>
                                <?php if (!empty($fields)) : ?>
                                    <?php foreach ($fields as $fieldName => $fieldLabel) : ?>
                                        <div class="col-md-6">
                                            <label class="col-form-label"><?php echo $fieldLabel ?></label>
                                            <div>
                                                <input class="form-control <?php echo $fieldName ?>" disabled type="text">
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <?php for ($i = 0; $i < 4; $i++): ?>
                <div class="flex-column" data-kt-stepper-element="content">
                    <div class="card card-custom card-sticky">
                        <div class="card-header">
                            <div class="card-title">
                                <h2><?php echo __('app.common.step_page') ?></h2>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">
                                    <div id="json-content-form-<?php echo $i ?>" class="json-content-form"></div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endfor; ?>

            <div data-kt-stepper-element="content">
                <div class="card card-custom card-sticky w-100">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.step_generate_pdf') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <?php $this->insert("inc/common/generated_files", [
                            'files' => !empty($data['recipeFiles']) ? $data['recipeFiles'] : [],
                            'downloadUrl' => '/app/recipe/pdf/file/',
                            'info' => __('app.recipe.pdf_versions_info')
                        ]) ?>
                    </div>
                </div>
            </div>
        </div>

        <?php $this->insert("inc/common/stepper_actions", ['cmyk' => true]) ?>
    </div>
</form>