<form
    id="mt-recipe-form"
    class="d-none data-form"
    data-js="RecipeForm"
    action="/app/recipe/save/<?php echo \App\Constant\App\FormSaveMode::SaveAndContinue ?>"
    method="post"
    autocomplete="off">
    <?php
    $this->insert(
        "inc/common/subheader",
        [
            'entity' => 'recipe',
            'btnBack' => '/app/recipes',
            'btnSave' => true,
            'menu' => $menu,
            'breadcumb' => $breadcumb
        ]
    );
    ?>
    <?php if (!empty($data['id'])): ?>
        <input type="hidden" name="id" value="<?php echo $data['id'] ?>" />
    <?php endif; ?>

    <div class="stepper stepper-pills first" id="mt-recipe-stepper">
        <?php $this->insert("inc/common/stepper_nav", ['steps' => [
            __('app.common.step_info'),
            __('app.common.step_page'),
            __('app.common.step_generate_pdf')
        ]]) ?>

        <div>
            <div class="current flex-column" data-kt-stepper-element="content">
                <div class="card card-custom card-sticky">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.main_information') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col md-6">
                                <label class="col-form-label required"><?php echo __('app.common.name') ?></label>
                                <div>
                                    <input type="text" class="form-control" required placeholder="<?php echo __('app.common.name') ?>" name="name" maxlength="45" />
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.visuals_language') ?></label>
                                <div>
                                    <select name="main_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['main_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>"
                                                <?php echo (!empty($data['default_main_language']) && $lang['id'] == $data['default_main_language']) ? 'selected' : '' ?>>
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.qr_language') ?></label>
                                <div>
                                    <select name="qr_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['qr_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>">
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (!empty($data['id'])): ?>
                    <div class="card card-custom card-sticky">
                        <div class="card-header">
                            <div class="card-title">
                                <h3><?php echo __('app.common.additional_info') ?></h3>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row profile-allow profile-A">

                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.creator') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="creator_name" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_created') ?></label>
                                    <div>
                                        <input class="form-control mt-date-created" disabled type="text">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_updated') ?></label>
                                    <div>
                                        <input class="form-control mt-date-updated" disabled type="text">
                                    </div>
                                </div>
                                <?php if (!empty($fields)) : ?>
                                    <?php foreach ($fields as $fieldName => $fieldLabel) : ?>
                                        <div class="col-md-6">
                                            <label class="col-form-label"><?php echo $fieldLabel ?></label>
                                            <div>
                                                <input class="form-control <?php echo $fieldName ?>" disabled type="text">
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <div class="flex-column" data-kt-stepper-element="content">
                <div class="card card-custom card-sticky">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.step_page') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <label class="col-form-label required"><?php echo __('app.layout') ?></label>
                                <div>
                                    <select name="recipe_layout_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['layouts'] as $layout): ?>
                                            <option value="<?php echo $layout['id'] ?>">
                                                <?php echo $layout['name'] ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-12">
                                <div id="json-content-form" class="json-content-form"></div>
                                <input type="hidden" name="json_data">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div data-kt-stepper-element="content">
                <div class="card card-custom card-sticky w-100">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.step_generate_pdf') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <?php $this->insert("inc/common/generated_files", [
                            'files' => !empty($data['recipeFiles']) ? $data['recipeFiles'] : [],
                            'downloadUrl' => '/app/recipe/pdf/file/',
                            'info' => __('app.recipe.pdf_versions_info')
                        ]) ?>
                    </div>
                </div>
            </div>
        </div>

        <?php $this->insert("inc/common/stepper_actions") ?>
    </div>
</form>