<form
    id="mt-booklet-form"
    class="d-none data-form"
    data-js="BookletForm"
    action="/app/booklet/save/<?php echo \App\Constant\App\FormSaveMode::SaveAndContinue ?>"
    method="post"
    autocomplete="off">
    <?php
    $this->insert(
        "inc/common/subheader",
        [
            'entity' => 'booklet',
            'btnBack' => '/app/booklets',
            'btnSave' => true,
            'menu' => $menu,
            'breadcumb' => $breadcumb
        ]
    );
    ?>
    <?php if (!empty($data['id'])): ?>
        <input type="hidden" name="id" value="<?php echo $data['id'] ?>" />
    <?php endif; ?>

    <div class="stepper stepper-pills first" id="mt-booklet-stepper">
        <div class="card card-custom">
            <div class="card-body py-4">
                <div class="stepper-nav flex-start flex-wrap">
                    <?php foreach (['info', 'page_2', 'page_3', 'page_4', 'generate_pdf'] as $i => $step): ?>
                        <div class="stepper-item pe-lg-2 pe-xl-8 my-4<?php if ($i == 0): ?> current<?php endif; ?>" data-kt-stepper-element="nav" data-kt-stepper-action="step">
                            <div class="stepper-wrapper d-flex align-items-center">
                                <div class="stepper-icon w-40px h-40px">
                                    <span class="stepper-number"><?php echo $i + 1 ?></span>
                                </div>
                                <div class="stepper-label">
                                    <h3 class="stepper-title">
                                        <?php echo __('app.booklet.step_' . $step) ?>
                                    </h3>
                                </div>
                            </div>
                            <div class="stepper-line h-40px"></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div>
            <div class="current flex-column" data-kt-stepper-element="content">
                <div class="card card-custom card-sticky">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.main_information') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col md-6">
                                <label class="col-form-label required"><?php echo __('app.common.name') ?></label>
                                <div>
                                    <input type="text" class="form-control" required placeholder="<?php echo __('app.common.name') ?>" name="name" maxlength="100" />
                                </div>
                            </div>

                            <?php if ($_SESSION['user']['user_profile_id'] == App\Constant\UserProfile::Administrator) : ?>
                                <div class="col-md-6">
                                    <label class="col-form-label required"><?php echo __('app.entity.market') ?></label>
                                    <div>
                                        <select name="market_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                            <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                            <?php foreach ($data['markets'] as $market): ?>
                                                <option value="<?php echo $market['id'] ?>">
                                                    <?php echo $market['name'] ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.entity.market') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="market_name" />
                                    </div>
                                </div>
                            <?php endif ?>

                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.visuals_language') ?></label>
                                <div>
                                    <select name="main_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['main_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>"
                                                <?php echo (!empty($data['default_main_language']) && $lang['id'] == $data['default_main_language']) ? 'selected' : '' ?>>
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-form-label required"><?php echo __('app.qr_language') ?></label>
                                <div>
                                    <select name="qr_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['qr_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>">
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (!empty($data['id'])): ?>
                    <div class="card card-custom card-sticky">
                        <div class="card-header">
                            <div class="card-title">
                                <h3><?php echo __('app.common.additional_info') ?></h3>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row profile-allow profile-A">

                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.creator') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="creator_name" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_created') ?></label>
                                    <div>
                                        <input class="form-control mt-date-created" disabled type="text">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_updated') ?></label>
                                    <div>
                                        <input class="form-control mt-date-updated" disabled type="text">
                                    </div>
                                </div>
                                <?php if (!empty($fields)) : ?>
                                    <?php foreach ($fields as $fieldName => $fieldLabel) : ?>
                                        <div class="col-md-6">
                                            <label class="col-form-label"><?php echo $fieldLabel ?></label>
                                            <div>
                                                <input class="form-control <?php echo $fieldName ?>" disabled type="text">
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <?php $this->insert("booklet/inc/page", ['pageNum' => 2, 'layouts' => $data['layouts']]) ?>
            <?php $this->insert("booklet/inc/page", ['pageNum' => 3, 'layouts' => $data['layouts']]) ?>
            <?php $this->insert("booklet/inc/page", ['pageNum' => 4, 'layouts' => $data['layouts']]) ?>

            <div data-kt-stepper-element="content">
                <div class="card card-custom card-sticky w-100">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.booklet.step_generate_pdf') ?></h2>
                        </div>
                    </div>
                    <div class="card-body file-info-container">
                        <div class="row">
                            <div class="col-12">
                                <div class="pb-1 border-bottom"><?php echo __('app.booklet.pdf_versions_info') ?></div>
                            </div>

                            <?php if (!empty($data['bookletFiles'])): ?>
                                <?php foreach ($data['bookletFiles'] as $i => $pdFile): ?>
                                    <?php if ($i == 0): ?>
                                        <div class="col-12 mb-3 h4"><?php echo __('app.booklet.pdf_versions_last') ?></div>
                                    <?php elseif ($i == 1): ?>
                                        <div class="col-12 mb-3 mt-5 h4 historical-title"><?php echo __('app.booklet.pdf_versions') ?></div>
                                    <?php endif; ?>
                                    <div class="col-sm-6 col-md-4 col-lg-3 mb-4 file-container">
                                        <a class="file-info d-block p-3 <?php if ($i == 0): ?>last-file<?php endif; ?>" href="/app/booklet/pdf/file/<?php echo $pdFile['id'] ?>" target="_blank">
                                            <div class="row">
                                                <div class="col-3">
                                                    <i class="la la-file-pdf"></i>
                                                </div>
                                                <div class="col-9">
                                                    <?php $fileDate = explode(' ', date('d/m/Y H:i:s', strtotime($pdFile['date']))) ?>
                                                    <div><?php echo $fileDate[0] ?></div>
                                                    <div><?php echo $fileDate[1] ?></div>
                                                </div>
                                            </div>
                                        </a>
                                        <?php if ($i > 0): ?>
                                            <a href="javascript:;" class="btn-delete-file" data-file-id="<?php echo $pdFile['id'] ?>"><i class="la la-trash"></i></a>
                                        <?php endif; ?>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--begin::Actions-->
        <div class="d-flex flex-stack container-fluid">
            <div class="me-2">
                <button type="button" class="btn btn-secondary" data-kt-stepper-action="previous">
                    <?php echo __('app.common.previous') ?>
                </button>
            </div>

            <div>
                <div class="dropdown project-dropdown" data-kt-stepper-action="submit">
                    <a href="javascript:;" data-submit-mode="<?php echo \App\Constant\App\FormSaveMode::SaveAndGenerate ?>" class="btn btn-primary btn rounded btn-rounded-grouped pe-2"><?php echo __('app.save.generate_pdf') ?></a><a href="javascript:;" class="btn btn-primary btn ms-0 ps-2 rounded btn-rounded-grouped dropdown-toggle" data-bs-toggle="dropdown">
                        <i class="ki-outline ki-down fs-3 ms-1"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end border-1 border-primary p-3">
                        <li><span class="dropdown-item py-3 text-primary bg-white"><?php echo __('app.common.options') ?>:</span></li>
                        <li>
                            <a href="javascript:;" data-submit-mode="<?php echo \App\Constant\App\FormSaveMode::SaveAndGenerate ?>" class="dropdown-item py-3">
                                <i class="nav-icon la la-file-pdf"></i>
                                <span class="nav-text"><?php echo __('app.save.save_generate_pdf') ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" data-submit-mode="<?php echo \App\Constant\App\FormSaveMode::SaveAndPreview ?>" class="dropdown-item py-3">
                                <i class="nav-icon la la-eye"></i>
                                <span class="nav-text"><?php echo __('app.save.save_preview_pdf') ?></span>
                            </a>
                        </li>
                    </ul>
                </div>

                <button type="button" class="btn btn-primary" data-kt-stepper-action="next">
                    <?php echo __('app.common.next') ?>
                </button>
            </div>
        </div>
        <!--end::Actions-->
    </div>
</form>