<form
    id="mt-booklet-form"
    class="d-none data-form"
    data-js="BookletForm"
    action="/app/booklet/save/<?php echo \App\Constant\App\FormSaveMode::SaveAndContinue ?>"
    method="post"
    autocomplete="off"
    data-default-market-id="<?php echo !empty($data['default_market_id']) ? $data['default_market_id'] : '' ?>">
    <?php
    $this->insert(
        "inc/common/subheader",
        [
            'entity' => 'booklet',
            'btnBack' => '/app/booklets',
            'btnSave' => true,
            'menu' => $menu,
            'breadcumb' => $breadcumb
        ]
    );
    ?>
    
    <?php if (!empty($data['id'])): ?>
        <input type="hidden" name="id" value="<?php echo $data['id'] ?>" />
    <?php else: ?>
        <input type="hidden" name="booklet_type_id" value="<?php echo $data['type'] ?>" />
    <?php endif; ?>

    <div class="stepper stepper-pills first" id="mt-booklet-stepper">
        <?php if($data['type'] == App\Constant\BookletType::Flyer): ?>
            <?php $this->insert("inc/common/stepper_nav", ['steps' => [
                __('app.common.step_info'),
                __('app.common.step_page') . ' ' . 1,
                __('app.common.step_page') . ' ' . 2,
                __('app.common.step_generate_pdf')
            ]]) ?>
        <?php else: ?>
            <?php $this->insert("inc/common/stepper_nav", ['steps' => [
                __('app.common.step_info'),
                __('app.common.step_page') . ' ' . 2,
                __('app.common.step_page') . ' ' . 3,
                __('app.common.step_page') . ' ' . 4,
                __('app.common.step_generate_pdf')
            ]]) ?>
        <?php endif; ?>

        <div>
            <div class="current flex-column" data-kt-stepper-element="content">
                <div class="card card-custom card-sticky">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.main_information') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col md-6">
                                <label class="col-form-label required"><?php echo __('app.common.name') ?></label>
                                <div>
                                    <input type="text" class="form-control" required placeholder="<?php echo __('app.common.name') ?>" name="name" maxlength="100" />
                                </div>
                            </div>

                            <?php if ($_SESSION['user']['user_profile_id'] == App\Constant\UserProfile::Administrator) : ?>
                                <div class="col-md-6">
                                    <label class="col-form-label required allow-save-invalid"><?php echo __('app.entity.market') ?></label>
                                    <div>
                                        <select name="market_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required allow-save-invalid>
                                            <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                            <?php foreach ($data['markets'] as $market): ?>
                                                <option value="<?php echo $market['id'] ?>">
                                                    <?php echo $market['name'] ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.entity.market') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="market_name" />
                                    </div>
                                </div>
                            <?php endif ?>

                            <div class="col-md-6">
                                <label class="col-form-label required allow-save-invalid"><?php echo __('app.visuals_language') ?></label>
                                <div>
                                    <select name="main_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required allow-save-invalid>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['main_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>">
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class="col-form-label required allow-save-invalid"><?php echo __('app.qr_language') ?></label>
                                <div>
                                    <select name="qr_language_id" data-control="select2" data-placeholder="<?php echo __('app.common.select_value') ?>" class="form-select kt-select2" required allow-save-invalid>
                                        <option disabled selected value> <?php echo __('app.common.select_value') ?> </option>
                                        <?php foreach ($data['qr_languages'] as $lang): ?>
                                            <option value="<?php echo $lang['id'] ?>">
                                                <?php echo __($lang['name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (!empty($data['id'])): ?>
                    <div class="card card-custom card-sticky">
                        <div class="card-header">
                            <div class="card-title">
                                <h3><?php echo __('app.common.additional_info') ?></h3>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row profile-allow profile-A">

                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.creator') ?></label>
                                    <div>
                                        <input type="text" class="form-control" disabled name="creator_name" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_created') ?></label>
                                    <div>
                                        <input class="form-control mt-date-created" disabled type="text">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="col-form-label"><?php echo __('app.common.date_updated') ?></label>
                                    <div>
                                        <input class="form-control mt-date-updated" disabled type="text">
                                    </div>
                                </div>
                                <?php if (!empty($fields)) : ?>
                                    <?php foreach ($fields as $fieldName => $fieldLabel) : ?>
                                        <div class="col-md-6">
                                            <label class="col-form-label"><?php echo $fieldLabel ?></label>
                                            <div>
                                                <input class="form-control <?php echo $fieldName ?>" disabled type="text">
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <?php $this->insert("booklet/inc/page", ['pageNum' => 2, 'layouts' => $data['layouts'], 'type' => $data['type']]) ?>
            <?php $this->insert("booklet/inc/page", ['pageNum' => 3, 'layouts' => $data['layouts'], 'type' => $data['type']]) ?>
            <?php if($data['type'] != App\Constant\BookletType::Flyer): ?>
                <?php $this->insert("booklet/inc/page", ['pageNum' => 4, 'layouts' => $data['layouts'], 'type' => $data['type']]) ?>
            <?php endif; ?>

            <div data-kt-stepper-element="content">
                <div class="card card-custom card-sticky w-100">
                    <div class="card-header">
                        <div class="card-title">
                            <h2><?php echo __('app.common.step_generate_pdf') ?></h2>
                        </div>
                    </div>
                    <div class="card-body">
                        <?php $this->insert("inc/common/generated_files", [
                            'files' => !empty($data['bookletFiles']) ? $data['bookletFiles'] : [],
                            'downloadUrl' => '/app/booklet/pdf/file/',
                            'info' => __('app.booklet.pdf_versions_info')
                        ]) ?>
                    </div>
                </div>
            </div>
        </div>

        <?php $this->insert("inc/common/stepper_actions", ['cmyk' => true]) ?>
    </div>
</form>