<!--begin::Quick links-->
<div data-bs-toggle="tooltip" title="<?php echo __("app.header.quick_links.title") ?>" class="d-flex align-items-center ms-1 ms-lg-3">
    <!--begin::Menu wrapper-->
    <div id="kt_quick_links" class="btn btn-icon btn-active-light-primary w-30px h-30px w-md-40px h-md-40px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">
        <i class="bi bi-clipboard-check fs-1"></i>
    </div>
    <!--begin::Menu-->
    <div class="menu menu-sub menu-sub-dropdown menu-column w-250px w-lg-450px" data-kt-menu="true">
        <!--begin:Nav-->
        <div class="row g-0">
            <!--begin:Item-->
            <div class="col-md-6 col-lg-4">
                <a id="btn-quick-modal-fault" class="d-flex flex-column flex-center h-100 p-6 bg-hover-light border-end border-bottom">
                    <span class="icon-container mb-2">
                        <i class="fa fa-calendar-day fa-2x h-35px"></i>
                    </span>
                    <span class="fs-6 fw-bold text-center text-gray-800 mb-0"><?php echo __('app.quick.add_visit'); ?></span>
                </a>
            </div>
            <!--end:Item-->
            <!--begin:Item-->
            <div class="col-md-6 col-lg-4">
                <a href="javascript:;" id="btn-quick-modal-contract" class="d-flex flex-column flex-center h-100 p-6 bg-hover-light border-bottom border-end">
                    <span class="icon-container mb-2">
                        <i class="fa fa-briefcase-medical fa-2x h-35px"></i>
                    </span>
                    <span class="fs-6 fw-bold text-center text-gray-800 mb-0"><?php echo __('app.quick.add_material'); ?></span>
                </a>
            </div>
            <!--end:Item-->
            <!--begin:Item-->
            <div class="col-md-12 col-lg-4">
                <a id="btn-quick-modal-framework-contract" class="d-flex flex-column flex-center h-100 p-6 bg-hover-light border-bottom">
                    <span class="icon-containermb-2">
                        <i class="fa fa-file-invoice-dollar fa-2x h-35px"></i>
                    </span>
                    <span class="fs-6 fw-bold text-center text-gray-800 mb-0"><?php echo __('app.quick.add_invoice'); ?></span>
                </a>
            </div>
            <!--end:Item-->
        </div>
        <!--end:Nav-->
    </div>
    <!--end::Menu-->
    <!--end::Menu wrapper-->
</div>
<!--end::Quick links-->	