<!--begin::User-->
<div class="d-flex align-items-center" id="kt_header_user_menu_toggle">
    <!--begin::Menu wrapper-->
    <div class="cursor-pointer symbol symbol-30px symbol-md-40px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">
        <img src="/app/user/avatar/<?php echo $_SESSION['user']['id'] ?>?t=<?php echo strtotime($_SESSION['user']['date_updated']) ?>" class="h-auto" />
    </div>
    <!--begin::Menu-->
    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-primary py-4 fs-6 border border-1 border-secondary user-menu mt-6" data-kt-menu="true">
        <!--begin::Menu item-->
        <div class="menu-item px-3">
            <div class="menu-content d-flex align-items-top px-3">
                <!--begin::Avatar-->
                <div class="symbol symbol-50px me-5 d-flex align-items-center">
                    <img src="/app/user/avatar/<?php echo $_SESSION['user']['id'] ?>?t=<?php echo strtotime($_SESSION['user']['date_updated']) ?>" class="h-auto" />
                </div>
                <!--end::Avatar-->
                <!--begin::Username-->
                <div class="d-flex flex-column">
                    <div class="fw-500 fs-5 mb-1"><?php echo $_SESSION['user']['name'] . ' ' . $_SESSION['user']['surnames'] ?></div>
                    <div class="mb-1"><span class="badge fw-lighter text-white" style="background-color: <?php echo $_SESSION['user']['user_profile_color'] ?>"><?php echo __('table.user_profile.' . $_SESSION['user']['user_profile_id']) ?></span></div>
                    <a href="mailto:<?php echo $_SESSION['user']['email'] ?>" class="text-muted fs-7 text-break text-hover-primary"><?php echo $_SESSION['user']['email'] ?></a>
                </div>
                <!--end::Username-->
            </div>
        </div>
        <!--end::Menu item-->
        <!--begin::Menu separator-->
        <div class="separator my-2"></div>
        <!--end::Menu separator-->
        <!--begin::Menu item-->
        <div class="menu-item px-5 ms-1 py-2">
            <a href="/app/profile" class="menu-link text-muted">
                <i class="ki-outline ki-profile-user fs-3 me-5"></i><?php echo __('app.header.profile') ?>
            </a>
        </div>                
        <!--end::Menu item-->
        <!--begin::Menu item-->
        <div class="menu-item px-5 ms-1 py-2">
            <a href="/app/logout" class="menu-link text-muted">             
                <i class="ki-outline ki-exit-right fs-3 me-5"></i><?php echo __('app.header.logout') ?>
            </a>
        </div>
    </div>
    <!--end::Menu-->
    <!--end::Menu wrapper-->
</div>
<!--end::User -->