<div id="kt_app_footer" class="app-footer">
    <!--begin::Footer container-->
    <div class="app-container container-fluid d-flex flex-column flex-md-row flex-center flex-md-stack py-3">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted fw-semibold me-1"><?php echo date('Y') ?> ©</span>
            <a href="https://www.gilsys.com/" target="_blank" class="text-gray-800 text-hover-primary"><?php echo $params['GILSYS'] ?> <?php echo __('app.footer.brand_text') ?></a>
        </div>
        <!--end::Copyright-->
        <!--begin::Version link-->
        <div class="text-dark order-2 order-md-1 ms-3">
            <a href="#" data-bs-toggle="modal" data-bs-target="#versionModal" class="text-gray-800 text-hover-primary">Detalles versión 1.2</a>
        </div>
        <!--end::Version link-->
    </div>
    <!--end::Footer container-->
</div>

<?php
function getComposerLibraries() {
    $composerLockPath = __DIR__ . '/../../../../../composer.lock';
    $composerLockContent = file_get_contents($composerLockPath);
    $composerData = json_decode($composerLockContent, true);
    $libraries = [];
    if (isset($composerData['packages']) && is_array($composerData['packages'])) {
        foreach ($composerData['packages'] as $package) {
            $libraries[] = [
                'name' => $package['name'],
                'version' => $package['version']
            ];
        }
    }
    return $libraries;
}
?>
<!-- Version Modal -->
<div class="modal fade" id="versionModal" tabindex="-1" aria-labelledby="versionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="versionModalLabel">PRM - Gestión de procesos - Miray Consulting</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <img src="/app/img/logo_gilsys.png" class="img-fluid mw-25">
                    <img src="/app/img/logo.png" class="img-fluid mw-25">
                </div>
                <p>Notas de versión 1.2 (Fecha de versión: 17/07/2024): </p>
                <ul>
                    <li>Cambiado sistema para trabajar con ID's de FK en lugar de traceid para vincular presupuestos con albaranes y pedidos de compra</li>                    
                    <li>Pasados campos necesarios para mostrar correctamente el iva y el importe al generar albarán</li>                    
                    <li>Corregidos decimales en el albarán de Factusol</li>                    
                    <li>Corregida importación de carácteres especiales en los clientes</li>           
                </ul>                
                <p>Notas de versión 1.1 (Fecha de versión: 11/07/2024) </p>
                <ul>
                    <li>Se prepara para que al cerrar un presupuesto desde Redmine, automáticamente se marque el Pedido de compra como enviado.</li>
                    <li>Se prepara para vincular presupuesto con albarán y pedido de compra en Factusol</li>                    
                    <li>Se corrige la sincronización de comentario en albarán</li>                    
                    <li>No generar albaran si en la issue de redmine se indica como "No sincronizar"</li>                    
                    <li>Se corrige el error que impide imprimir albaranes generados automáticamente con el sistema.</li>                    
                </ul>                
                <p>Notas de versión 1.0 (Fecha de versión: 01/05/2024)</p>
                <ul>
                    <li>Branch para Miray, permite gestionar clientes y sus procesos asociados.</li>
                    <li>Clasifica cada proceso en tipologías personalizables.</li>
                    <li>Preestablece tareas pendientes al crear procesos según la tipología definida.</li>
                    <li>Facilita la introducción de información detallada para cada proceso.</li>
                    <li>Permite asignar tareas específicas a los procesos.</li>
                    <li>Ofrece un sistema inteligente de tags para etiquetar tareas.</li>
                    <li>Cuenta con funciones avanzadas de búsqueda y filtrado.</li>
                    <li>Comunica automáticamente información entre FACTUSOL y REDMINE.</li>
                    <li>Scripts importan presupuestos aceptados en FACTUSOL a PRM y los dan de alta en REDMINE.</li>
                    <li>Proyectos cerrados en REDMINE se importan a PRM y se exportan a FACTUSOL como albarán.</li>
                    <li>Sincroniza peticiones creadas en REDMINE para generar automáticamente albaranes en FACTUSOL.</li>
                </ul>
                <p>Versiones de librerías: </p>
                <div class="row">
                    <?php
                    $libraries = getComposerLibraries();
                    $half = ceil(count($libraries) / 2);
                    ?>
                    <div class="col-md-6">
                        <ul>
                            <?php for ($i = 0; $i < $half; $i++) : ?>
                                <li><?php echo $libraries[$i]['name'] . ': ' . $libraries[$i]['version']; ?></li>
                            <?php endfor; ?>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul>
                            <?php for ($i = $half; $i < count($libraries); $i++) : ?>
                                <li><?php echo $libraries[$i]['name'] . ': ' . $libraries[$i]['version']; ?></li>
                            <?php endfor; ?>
                        </ul>
                    </div>
                </div>

                <p>Versión de recursos: <?php echo RESOURCES_VERSION ?></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">
                    Actualizado a última versión: 1.2
                </button>                
            </div>
        </div>
    </div>
</div>