<!-- begin::Global Config(global config for global JS sciprts) -->
<script>
    var RESOURCES_VERSION = <?php echo RESOURCES_VERSION ?>;
</script>

<!-- Parámetros globales que interesa cargar para poder trabajar desde javascript-->
<script>
    PASSWORD_COMPLEX = <?php echo $params['PASSWORD_COMPLEX'] == '0' ? 'false' : 'true' ?>;
    PIN_LENGTH = <?php echo $params['PIN_LENGTH'] ?>;
</script>

<!--begin::Global Theme Bundle(used by all pages) -->		
<script src="/app/assets/plugins/global/plugins.bundle.js" type="text/javascript"></script>
<script src="/app/assets/js/scripts.bundle.js" type="text/javascript"></script>
<script src="/app/assets/plugins/custom/formrepeater/formrepeater.bundle.js" type="text/javascript"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-pincode-input@3.0.1/css/bootstrap-pincode-input.css" integrity="sha256-AHXxCeFPWpMDcs9gdJ1oT9oj0KvyTvQr5KT8yMzLTcU=" crossorigin="anonymous">
<script src="/app/js/lib/bootstrap-pincode-input.js" type="text/javascript"></script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" integrity="sha256-oA6D/yIi0I8ZwAwp6HmdjN7OoIOJ/6k+1SISncrEBQA=" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js" integrity="sha256-5N4FHlS7bWyb2LyIzO+TQ3eHNvb/vfEEjcdADdIvVTY=" crossorigin="anonymous"></script>

<!--end::Global Theme Bundle -->

<script src="/app/js/admin.utils.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>
<script src="/app/js/main.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>
<script src="/app/js/project.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>
<script src="/app/js/modal.alerts.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>
<script src="/app/js/lib/jscolor.min.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>

<script src="/app/js/i18n.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>
<script src="/app/js/lib/jsoneditor.i18n.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>

<!-- Traducciones importadas directamente en CA -->
<?php if (__('app.js.lang.code') == 'ca'): ?>
    <script src="/app/js/select2.ca.js" type="text/javascript"></script>
    <script src="/app/js/jquery.validator.ca.js" type="text/javascript"></script>
<?php endif; ?>

<script src="/app/js/bootstrap-datepicker.i18n.js<?php echo '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>

<?php if (!empty($js)): ?>
    <?php foreach ($js as $jsFile): ?>
        <script src="/app<?php echo $jsFile . '?v=' . RESOURCES_VERSION ?>" type="text/javascript"></script>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($debug) : ?>
    <?php $this->insert("inc/debug"); ?>
<?php endif; ?> 

<?php $this->insert("inc/iframe_modal"); ?>
<?php $this->insert("inc/pin_modal"); ?>
<?php $this->insert("inc/captcha", compact('params')); ?>
<?php if (!empty($jscustom)): ?>
    <script type="text/javascript">
    $(document).ready(function () {
    <?php echo $jscustom ?>
    });
    </script>
<?php endif; ?>
<?php if (!empty($common['jsFromSession'])): ?>
    <script type="text/javascript">
    <?php echo $common['jsFromSession'] ?>
    </script>
<?php endif; ?>
</body>
<!-- end::Body -->
</html>
